### ISSUE TITLE
assign key to a transformation

### ISSUE THREAD

**Issue by faridcher** [tbfisher/sublimetext-Pandoc#51] opened 2017-01-10 06:56 UTC
is it possible to bind a key to a specific transformation i.e. HTML. I know how to assign shortkey to a command in sublime text but don't know to assign it to a prompt (`pandoc_prompt`)

**Comment by pchtsp** [comment] 2017-10-26 14:10
Not sure if it's possible to do it with the current code... but a possible workaround is to do the following:

#60

**Comment by MPvHarmelen** [comment] 2020-05-01 12:39
This currently isn't possible. I'll close this issue because it's a duplicate of #60 and there's more discussion there.

**Closed by MPvHarmelen** 2020-05-01 12:39 UTC
